### ISSUE TITLE
VSX version of vpx_subtract_block

### ISSUE THREAD

**Issue by luctrudeau** [lu-zero/libvpx#20]
Implement a VSX version of vpx_subtract_block.

- [x] It must pass the VP9SubtractBlockTest suite
- [x] Add Speed Test to the VP9SubtractBlockTest suite (Disabled by default)
- [x] Report performance in commit msg (compared to C version)
  - Must show significant speedup over C version

**Comment by lu-zero** [comment]
[Merged](https://chromium-review.googlesource.com/c/webm/libvpx/+/1090170/4)
