### ISSUE TITLE
Implement the hadamard

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/libvpx#6]

**Comment by rafaeldelucena** [comment]
The first version for review is #16

**Comment by rafaeldelucena** [comment]
Waiting for https://chromium-review.googlesource.com/450878

**Comment by rafaeldelucena** [comment]
Pushing to upstream https://chromium-review.googlesource.com/c/450878

**Comment by rafaeldelucena** [comment]
@edelsohn

There's any VM infrastructure that IBM can make available to WebM community? Aiming to check builds and make part of continuous integration system from this project?

I've talk with Johann Koenig, one member of WebM community, to initially request some vms from http://osuosl.org, but in the long run would not that be a problem?

**Comment by edelsohn** [comment]
OSUOSL is the right place to request VMs for CI testers.

**Comment by rafaeldelucena** [comment]
Ok

**Comment by rafaeldelucena** [comment]
Added to upstream :tada: 

https://chromium.googlesource.com/webm/libvpx/+/cd3d7cf4acd47f13e65ba5d644aafe15fd340590
https://chromium.googlesource.com/webm/libvpx/+/405b94c661563d3ebcf57751da3b83ca943d2bcf

**Comment by lu-zero** [comment]
Great!

**Comment by rafaeldelucena** [comment]
@lu-zero 

Both PR merged to upstream are enough to finish these issues?

**Comment by lu-zero** [comment]
Indeed!
