### ISSUE TITLE
Implement the quantize

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/libvpx#9]

**Comment by lu-zero** [comment]
@luctrudeau I had that halfway since ages, if you want to take it over please do :)

**Comment by luctrudeau** [comment]
Done!

In https://chromium.googlesource.com/webm/libvpx/+/1251bf2a6383e326197a5b70c87d12f5cf4db904 I implemented a VSX version of quantization for 4x4, 8x8 and 16x16 blocks.
Considerable speeds ups to quantization have landed in  https://chromium.googlesource.com/webm/libvpx/+/81a98509dcd44e939656d8c281e5a5ae5b9926be
Finally the 32x32 variant of quantization landed in https://chromium.googlesource.com/webm/libvpx/+/d1aede92ec35f6adceb0c148dedcccc594fce166

VP9QuantizeTest Speed Test (POWER8 Model 2.1)
4x4: C time = 900 ms, VSX time = 141 ms (~7x)
8x8: C time = 818 ms, VSX time = 81 ms (~10x)
16x16: C time = 786 ms, VSX time = 64 ms (~12x)
32x32: C time = 1456 ms, VSX time = 80 ms (~18x)
